// This file is auto-generated by the Supabase CLI.
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/types/database.ts
// For now this is a placeholder so the Supabase clients compile.

export type Database = {
  public: {
    Tables: {
      videos: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      rooms: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      players: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      answers: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      votes: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
